### ISSUE TITLE
Crash error report - Possibly out of RAM?

### ISSUE THREAD

**Issue by Intuos5** [SMoG-Chalmers/PST#4]
When performing a calculation, 400m walking distance integration analysis, the plugin crashed:
It appears to be a RAM issue though, since a smaller test network didn't exhibit this issue. 
The area I attempted to calculate measured 23 x 21 kilometres.

The error message is as follows: 
An error has occurred while executing Python code: 

OSError: [WinError -529697949] Windows Error 0xe06d7363 
Traceback (most recent call last):
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pst\ui\pages\progresspage.py", line 85, in start
    task.run(dlgt)
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pst\analyses\networkintegrationanalysis.py", line 98, in run
    pstalgo.NetworkIntegration(
  File "C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pst\pstalgo\python\pstalgo\networkintegration.py", line 83, in NetworkIntegration
    if not fn(byref(desc)):
OSError: [WinError -529697949] Windows Error 0xe06d7363

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.4-Białowieża Białowieża, ce8e65e9 

Python Path:
C:/PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.4\bin\python39.zip
C:\PROGRA~1\QGIS32~1.4\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib
C:\Program Files\QGIS 3.22.4\bin
C:\PROGRA~1\QGIS32~1.4\apps\Python39
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\Pythonwin
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pst\pstalgo\python
E:/Folder/Folder

**Comment by Intuos5** [comment]
What I find particularly strange is that DepthmapX requires about half a GB of RAM, whereas Place Syntax Tools has used upwards to 99% of 32 GB RAM, it had at least access to 20 GB, which is still 40x the amount of DepthmapX for the same calculation. That is, if RAM was indeed the issue.

**Comment by double-u-a** [comment]
DepthmapX is single threaded, inaccurate and slow, it doesn't use many resources because it doesn't know to use them effectively.

**Comment by giannastavroulaki** [comment]
Apologies for the late reply. 
I hope that you have downloaded the latest versions (latest 3.2.5) and that this issue has been resolved. 

The network you tried to analyse is not too large for PST and it shouldn't crash. Especially since you used such a small radius. Please let us know if there are still issues and resend us the error, specifying the PST version you used.

Gianna,
on behalf of the SMoG
